<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

// Create a shortcut for params.
$params = $this->item->params;
JHtml::addIncludePath(JPATH_COMPONENT . '/helpers/html');
$canEdit = $this->item->params->get('access-edit');
$info    = $params->get('info_block_position', 0);
$img = json_decode($this->item->images);

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_associations'));

?>
<?php if ($this->item->state == 0 || strtotime($this->item->publish_up) > strtotime(JFactory::getDate())
	|| ((strtotime($this->item->publish_down) < strtotime(JFactory::getDate())) && $this->item->publish_down != JFactory::getDbo()->getNullDate())) : ?>
	<div class="system-unpublished">
<?php endif; ?>

<?php if ($canEdit || $params->get('show_print_icon') || $params->get('show_email_icon')) : ?>
	<?=JLayoutHelper::render('joomla.content.icons', array('params' => $params, 'item' => $this->item, 'print' => false)); ?>
<?php endif; ?>

<?php // Todo Not that elegant would be nice to group the params ?>
<?php $useDefList = ($params->get('show_modify_date') || $params->get('show_publish_date') || $params->get('show_create_date')
	|| $params->get('show_hits') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author') || $assocParam); ?>

	<?php if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
		<?=JLayoutHelper::render('joomla.content.tags', $this->item->tags->itemTags); ?>
	<?php endif; ?>

<a href="#list-<?=$this->item->id;?>" aria-controls="#list-<?=$this->item->id;?>" data-toggle="collapse" data-toggle="button" class="link d-flex align-items-end list-group-item" role="button" aria-expanded="false" aria-label="<?=JText::_('JGLOBAL_EXPAND_CATEGORIES'); ?>">
	<?php if ($useDefList && ($info == 0 || $info == 2)) : ?>
		<?=JLayoutHelper::render('joomla.content.info_block', array('item' => $this->item, 'params' => $params, 'position' => 'above')); ?>
	<?php endif; ?>
	<div class="flex-grow-1" itemprop="name">
		<h3><?=$this->item->title;?></h3>
		<?php //echo JLayoutHelper::render('joomla.content.blog_style_default_item_title', $this->item); ?>
	</div>
	<div class="flex-shrink-1 ml-auto">
		<span class="check"></span>	
	</div>
</a>
<div class="list-niokr my-4 media row collapse" id='list-<?=$this->item->id;?>'>
	<?php if (!empty($this->item->text && $img->image_intro)):
		$col5 = '4';
		$col7 = '8';
	else : 
		$col5 = '12';
		$col7 = '12';
	endif; ?>

<?php //echo JLayoutHelper::render('joomla.content.intro_image', $this->item); ?>
<?php if (isset($img->image_intro) && !empty($img->image_intro)) : ?>
	<div class="col-12 col-lg-<?=$col5?> mr-3"><img src="<?=htmlspecialchars($img->image_intro, ENT_COMPAT, 'UTF-8');?>" itemprop="image"
		<?php 
		if (!empty($img->img_intro_alt)) :
			echo ' alt="' . htmlspecialchars($img->img_intro_alt, ENT_COMPAT, 'UTF-8') . '"';
		else :
			echo ' alt="' . mb_strtolower(htmlspecialchars($this->item->title, ENT_COMPAT, 'UTF-8')) . '"';
		endif;
		if (!empty($img->img_intro_caption)) :
			echo ' title="' . htmlspecialchars($img->img_intro_caption, ENT_COMPAT, 'UTF-8') . '"';
		else :
			echo ' title="' . mb_strtolower(htmlspecialchars($this->item->title, ENT_COMPAT, 'UTF-8')) . '"';
		endif;
		?>
	></div>
<?php endif; ?>
	<div class="col-12 col-lg-<?=$col7?> media-body">
		<?php if ($info == 1 || $info == 2) : ?>
			<?php if ($useDefList) : ?>
				<?php // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block ?>
				<?=JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'below')); ?>
			<?php endif; ?>
			<?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
				<?=JLayoutHelper::render('joomla.content.tags', $this->item->tags->itemTags); ?>
			<?php endif; ?>
		<?php endif; ?>
		<?php if (!$params->get('show_intro')) : ?>
			<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
			<?=$this->item->event->afterDisplayTitle; ?>
		<?php endif; ?>
		<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
		<?=$this->item->event->beforeDisplayContent; ?>
		<?=$this->item->text; ?>
		<?php // echo $this->item->introtext; ?>
		<?php if ($params->get('show_readmore') && $this->item->readmore) :
			if ($params->get('access-view')) :
				$link = JRoute::_(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language));
			else :
				$menu = JFactory::getApplication()->getMenu();
				$active = $menu->getActive();
				$itemId = $active->id;
				$link = new JUri(JRoute::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false));
				$link->setVar('return', base64_encode(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language)));
			endif; ?>
			<?=JLayoutHelper::render('joomla.content.readmore', array('item' => $this->item, 'params' => $params, 'link' => $link)); ?>
		<?php endif; ?>		
	</div>
	<div class="col-12 pt-2">
	<a href="#list-<?=$this->item->id;?>" aria-controls="#list-<?=$this->item->id;?>" data-toggle="collapse" data-toggle="button" class="link d-flex justify-content-end" role="button" aria-expanded="false" aria-label="<?=JText::_('JHIDE'); ?>"><?=JText::_('JHIDE'); ?></a>
	</div>
</div>
<?php if ($this->item->state == 0 || strtotime($this->item->publish_up) > strtotime(JFactory::getDate())
	|| ((strtotime($this->item->publish_down) < strtotime(JFactory::getDate())) && $this->item->publish_down != JFactory::getDbo()->getNullDate())) : ?>
</div>
<?php endif; ?>

<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
<?=$this->item->event->afterDisplayContent; ?>