<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');
$params = $this->params;
?>

<div class="articles<?=$this->pageclass_sfx; ?>">
	<div class="list-group list-group-flush mb-4">
	<?php foreach ($this->items as $i => $item) : ?>
		<?php $info = $item->params->get('info_block_position', 0); ?>
<div class="article list-<?=$i;?>" itemscope itemtype="https://schema.org/Article">
	<a href="#list-<?=$i; ?>" aria-controls="list-<?=$i; ?>" data-toggle="collapse" data-toggle="button" class="link list-group-item" role="button" aria-expanded="false" aria-label="<?=JText::_('JGLOBAL_EXPAND_CATEGORIES'); ?>">
		<?=$this->loadTemplate('date'); ?>

				<div class="article-list flex-grow-1" itemprop="headline">
					<h3 class="title"><?=$this->escape($item->title); ?></h3>
					<?=$item->event->afterDisplayTitle; ?>
				</div>
						<?php /*if ($params->get('link_titles')) : ?>
							<a href="<?=JRoute::_(ContentHelperRoute::getArticleRoute($item->slug, $item->catid, $item->language)); ?>" itemprop="url">
								<?=$this->escape($item->title); ?>
							</a>
						<?php else : ?>
							<?=$this->escape($item->title); ?>
						<?php endif; */?>
					<?php /*if ($params->get('show_author') && !empty($item->author )) : ?>
						<div class="createdby" itemprop="author" itemscope itemtype="https://schema.org/Person">
						<?php $author = $item->created_by_alias ?: $item->author; ?>
						<?php $author = '<span itemprop="name">' . $author . '</span>'; ?>
							<?php if (!empty($item->contact_link) && $params->get('link_author') == true) : ?>
								<?=JText::sprintf('COM_CONTENT_WRITTEN_BY', JHtml::_('link', $this->item->contact_link, $author, array('itemprop' => 'url'))); ?>
							<?php else : ?>
								<?=JText::sprintf('COM_CONTENT_WRITTEN_BY', $author); ?>
							<?php endif; ?>
						</div>
					<?php endif;*/ ?>
				
			<div class="flex-shrink-1 ml-auto">
				<span class="check"></span>	
			</div>	
	</a>
			<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
			<?=$item->event->beforeDisplayContent; ?>

		<div class="intro collapse" id="list-<?=$i; ?>"  itemprop="articleBody">
		<?php $img = json_decode($item->images); ?>
		<?php if (!empty($item->introtext && $img->image_intro)): // если описание и картинка есть
			$colImg = 'col-4 col-lg-3';
			$colDesc = 'col-8 col-lg-9';
		else : 
			$colImg = $colDesc = 'col-12';
		endif; ?>
		<?php if (isset($img->image_intro) && !empty($img->image_intro)) : ?>
			<div class="img <?=$colImg;?>">	
				<a href="<?=JRoute::_(ContentHelperRoute::getArticleRoute($item->slug, $item->catid, $item->language)); ?>" itemprop="url">
		<img src="<?=htmlspecialchars($img->image_intro, ENT_COMPAT, 'UTF-8');?>" itemprop="image"
			<?php 
			if (!empty($img->img_intro_alt)) :
				echo ' alt="' . htmlspecialchars($img->img_intro_alt, ENT_COMPAT, 'UTF-8') . '"';
			else :
				echo ' alt="' . str_replace('"', '', mb_strtolower(htmlspecialchars(JHtml::_('string.truncate',$this->item->title,(int)25,false,false), ENT_COMPAT, 'UTF-8'))) . '"';
			endif;
			if (!empty($img->img_intro_caption)) :
				echo ' title="' . htmlspecialchars($img->img_intro_caption, ENT_COMPAT, 'UTF-8') . '"';
			else :
				echo ' title="' . str_replace('"', '', mb_strtolower(htmlspecialchars(JHtml::_('string.truncate',$this->item->title,(int)25,false,false), ENT_COMPAT, 'UTF-8'))) . '"';
			endif;?> 
			class="img-fluid"></a>
			</div>
		<?php endif; ?>
			<?php if ($params->get('show_intro')) : ?>
				<div class="desc <?=$colDesc;?>">
					<?=JHtml::_('string.truncateComplex', $item->introtext, $params->get('introtext_limit')); ?>
				</div>
			<?php endif; ?>
			<div class="readmore">
			<a class="btn" href="<?=JRoute::_(ContentHelperRoute::getArticleRoute($item->slug, $item->catid, $item->language)); ?>" aria-label="<?=$item->title?>" itemprop="url"><?=JText::sprintf('COM_CONTENT_READ_MORE_TITLE'); ?></a>
			</div>
		</div>
</div>
			<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
			<?=$item->event->afterDisplayContent; ?>
	<?php endforeach; ?>
</div>	
	<div class="pagination">
		<p class="counter"> <?=$this->pagination->getPagesCounter(); ?> </p>
		<?=$this->pagination->getPagesLinks(); ?>
	</div>	
</div>
